[tools]
bun = "latest"
deno = "latest"
docker-cli = "latest"
github-cli = "latest"
node = "22.17.0"
pnpm = "latest"
python = "3.13"
terraform = "latest"
uv = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
