@startuml keisuke

left to right direction
hide circle
hide empty members

mix_actor 受注者
mix_actor 発注者
class 受注者プロフィール
class 発注者プロフィール
class アドバイス
class 職歴
class 案件
class スカウト案件
class 公募案件
class 案件下書き
class スカウトリスト
class チャットルーム
class メッセージ

受注者 o--> "1" 受注者プロフィール
受注者 o--> "0.." アドバイス
受注者 o--> "0.." 職歴
受注者 o--> チャットルーム
発注者 o--> 発注者プロフィール
発注者 o-- チャットルーム
発注者 o-- 案件
案件 <|-- 公募案件
案件 <|-- スカウト案件
案件 <|-- 案件下書き
スカウト案件 o-- スカウトリスト
チャットルーム o-- メッセージ

@enduml
